"""The evidence command line: one entry point, several verbs, no ambient state.

Usage from `scripts/validation`:

    PYTHONPATH=. python -m evidence baseline --markdown
    PYTHONPATH=. python -m evidence taxonomy
    PYTHONPATH=. python -m evidence selftest
    PYTHONPATH=. python -m evidence view --audience medical_director --store /srv/fk/evidence.jsonl

Two conventions worth stating because they are the whole point of the tool:

**Exit codes are decisions.** 0 means the answer is clean; 1 means something must be read
before proceeding (a regression gate failed, an export refused, a store is inside the tree);
2 means the command was not run correctly. A CI job can therefore use this as a gate rather
than a log.

**No command invents data to be interesting.** Where a measurement needs a session store, a
model, or a clinician and does not have one, the command says so and exits. A report filled
with zeros reads exactly like a report that found nothing, and the difference matters to
anyone deciding whether to turn a feature on.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import baseline, groundtruth, loops, regression, reporting, scoring, stats, store, taxonomy


def _emit(payload) -> int:
    text = (
        payload
        if isinstance(payload, str)
        else json.dumps(payload, indent=2, sort_keys=True, default=str)
    )
    print(text)
    return 0


def cmd_baseline(args: argparse.Namespace) -> int:
    summary = baseline.run()
    return _emit(baseline.markdown_table(summary) if args.markdown else summary)


def cmd_taxonomy(args: argparse.Namespace) -> int:
    if args.markdown:
        lines = [
            "<!-- GENERATED by `python -m evidence taxonomy --markdown` — "
            "the code is the authority. -->",
            "",
            "| Code | Name | Group | Detected by | Engine checks | Fix target | Default |",
            "| --- | --- | --- | --- | --- | --- | --- |",
        ]
        for item in taxonomy.CLASSES:
            lines.append(
                f"| `{item.code}` | {item.name} | {item.group} | {item.detected_by} | "
                f"{', '.join(item.engine_checks) or '—'} | "
                f"{item.fix_target} | {item.default_severity} |"
            )
        lines += [
            "",
            "Engine visibility over the taxonomy:",
            "```json",
            json.dumps(taxonomy.engine_coverage(), indent=2, sort_keys=True),
            "```",
        ]
        return _emit("\n".join(lines) + "\n")
    return _emit(
        {
            "classes": [
                item.as_dict() if hasattr(item, "as_dict") else item.__dict__
                for item in taxonomy.CLASSES
            ],
            "coverage": taxonomy.engine_coverage(),
            "unmapped_engine_checks": sorted(taxonomy.unmapped_engine_checks()),
            "unknown_engine_checks": sorted(taxonomy.unknown_engine_checks()),
        }
    )


def cmd_selftest(_: argparse.Namespace) -> int:
    """Known-answer checks, so the package can be proved correct with no clinical data at all."""
    checks: list[tuple[str, bool]] = []
    checks.append(
        (
            "wilson 5/10",
            tuple(round(value, 4) for value in stats.wilson_interval(5, 10)) == (0.2366, 0.7634),
        )
    )
    mcnemar = stats.mcnemar(15, 2)
    checks.append(("mcnemar exact p", abs(mcnemar.p_value - 0.00235) < 1e-4))
    checks.append(
        (
            "mde halves when n quadruples",
            abs(stats.mde_paired(200).estimate * 2 - stats.mde_paired(50).estimate) < 0.01,
        )
    )
    holm = stats.holm([("a", 0.01), ("b", 0.04), ("c", 0.03)])
    checks.append(
        (
            "holm orders and adjusts",
            holm[0]["adjusted"] <= holm[-1]["adjusted"] and holm[0]["name"] == "a",
        )
    )
    checks.append(("taxonomy maps every engine check", not taxonomy.unmapped_engine_checks()))
    checks.append(("taxonomy invents no check", not taxonomy.unknown_engine_checks()))
    checks.append(("E99 exists", taxonomy.code("E99").name == "unclassified"))
    try:
        stats.assert_not_combined() if hasattr(
            stats, "assert_not_combined"
        ) else scoring.assert_not_combined()
        checks.append(("combined score refused", False))
    except scoring.CombinedScoreError:
        checks.append(("combined score refused", True))
    try:
        loops.apply()
        checks.append(("auto-apply refused", False))
    except loops.AutoApplyError:
        checks.append(("auto-apply refused", True))
    failed = [name for name, passed in checks if not passed]
    print(f"{len(checks) - len(failed)} of {len(checks)} evidence self-tests pass")
    for name in failed:
        print(f"  FAILED: {name}")
    return 0 if not failed else 1


def cmd_groundtruth(args: argparse.Namespace) -> int:
    cases = [groundtruth.from_golden(row) for row in baseline.load_cases()]
    return _emit(groundtruth.corpus_summary(cases))


def _load_store(path: str) -> list[dict]:
    return store.read(Path(path))


def cmd_view(args: argparse.Namespace) -> int:
    return _emit(reporting.view(_load_store(args.store), args.audience))


def cmd_check(args: argparse.Namespace) -> int:
    rows = _load_store(args.store)
    verdict = reporting.anonymise_check(rows)
    print(json.dumps(verdict, indent=2, sort_keys=True))
    print(json.dumps(reporting.centre_summary(rows), indent=2, sort_keys=True))
    return 1 if verdict["verdict"].startswith("refused") else 0


def cmd_tables(args: argparse.Namespace) -> int:
    rows = _load_store(args.store)
    return _emit(
        {"table_1": reporting.table_1(rows), "results": reporting.results_table(rows, args.success)}
    )


def cmd_figure(args: argparse.Namespace) -> int:
    from . import longitudinal

    points = longitudinal.series(_load_store(args.store), args.metric, args.period)
    return _emit(reporting.svg_line(points, value_key="mean") if args.svg else points)


def cmd_regress(args: argparse.Namespace) -> int:
    payload = json.loads(Path(args.paired).read_text(encoding="utf-8"))
    report = regression.compare(payload, regression.DEFAULT_ENDPOINTS)
    print(json.dumps(report.as_dict(), indent=2, sort_keys=True))
    return 0 if report.passed else 1


def cmd_loop_state(_: argparse.Namespace) -> int:
    return _emit(loops.loop_state())


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="evidence", description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    baseline_p = sub.add_parser("baseline", help="measure the corpus the repository already has")
    baseline_p.add_argument("--markdown", action="store_true")
    baseline_p.set_defaults(func=cmd_baseline)

    taxonomy_p = sub.add_parser("taxonomy", help="print the error taxonomy and its engine coverage")
    taxonomy_p.add_argument("--markdown", action="store_true")
    taxonomy_p.set_defaults(func=cmd_taxonomy)

    ground_p = sub.add_parser(
        "groundtruth", help="how much of the corpus is usable as evidence about care"
    )
    ground_p.set_defaults(func=cmd_groundtruth)

    selftest_p = sub.add_parser("selftest", help="known-answer checks, no data required")
    selftest_p.set_defaults(func=cmd_selftest)

    loop_p = sub.add_parser("loop-state", help="what each improvement loop can do today")
    loop_p.set_defaults(func=cmd_loop_state)

    view_p = sub.add_parser("view", help="one audience's view of a session store")
    view_p.add_argument("--audience", required=True, choices=sorted(reporting.AUDIENCES))
    view_p.add_argument("--store", required=True)
    view_p.set_defaults(func=cmd_view)

    check_p = sub.add_parser("check", help="anonymisation gate and between-centre summary")
    check_p.add_argument("--store", required=True)
    check_p.set_defaults(func=cmd_check)

    tables_p = sub.add_parser("tables", help="Table 1 and stratified results with intervals")
    tables_p.add_argument("--store", required=True)
    tables_p.add_argument(
        "--success", required=True, help="field name treated as the success event"
    )
    tables_p.set_defaults(func=cmd_tables)

    figure_p = sub.add_parser("figure", help="trend series, optionally as reviewable SVG")
    figure_p.add_argument("--store", required=True)
    figure_p.add_argument("--metric", required=True)
    figure_p.add_argument("--period", default="month")
    figure_p.add_argument("--svg", action="store_true")
    figure_p.set_defaults(func=cmd_figure)

    regress_p = sub.add_parser("regress", help="the four-gate regression verdict for a paired run")
    regress_p.add_argument(
        "--paired", required=True, help="JSON list of {case_ref, baseline, candidate}"
    )
    regress_p.set_defaults(func=cmd_regress)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return args.func(args)
    except (store.StoreError, groundtruth.RecordError) as error:
        print(f"refused: {error}", file=sys.stderr)
        return 1
